/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function lookupLocalization(identifier: string, language?: string | undefined | null): string | null

export declare function readDatacoreRecordByGuid(guid: string): any

export declare function readDatacoreRecordByPath(recordPath: string): any

export declare function readDatacoreRecordsByType(recordType: string): Array<any>

export declare function readSocpak(socpakPath: string): any
